# Generated by Django 5.0.7 on 2025-10-30 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0002_emailchangerequest'),
        ('pedidos', '0004_pedido_cotacao_custo_beneficio_tempo_and_more'),
        ('rotas', '0001_initial'),
        ('veiculos', '0002_veiculo_categoria_minima_cnh_veiculo_sede_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh_categoria', models.CharField(choices=[('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E')], help_text='Categoria da Carteira Nacional de Habilitação', max_length=1, verbose_name='Categoria CNH')),
                ('disponivel', models.BooleanField(default=True, help_text='Indica se o motorista está disponível para entregas', verbose_name='Disponível')),
                ('entregas_concluidas', models.IntegerField(default=0, help_text='Contador de entregas realizadas com sucesso', verbose_name='Entregas Concluídas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to='contas.profile', verbose_name='Perfil de Usuário')),
                ('sede_atual', models.ForeignKey(help_text='Cidade onde o motorista está atualmente disponível', on_delete=django.db.models.deletion.PROTECT, related_name='motoristas', to='rotas.cidade', verbose_name='Sede Atual')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['-entregas_concluidas', 'profile__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicao', to='pedidos.pedido', verbose_name='Pedido')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='veiculos.veiculo', verbose_name='Veículo')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='motoristas.motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Atribuição de Pedido',
                'verbose_name_plural': 'Atribuições de Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
