# Generated by Django 5.0.7 on 2025-10-30 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('veiculo', 'Problema com Veículo'), ('carga', 'Problema com Carga'), ('rota', 'Problema na Rota'), ('cliente', 'Problema com Cliente'), ('acidente', 'Acidente'), ('outro', 'Outro')], help_text='Categoria do problema', max_length=20, verbose_name='Tipo de Problema')),
                ('descricao', models.TextField(help_text='Descrição detalhada do problema encontrado', verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('resolvido', 'Resolvido')], default='pendente', help_text='Status atual do problema', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('resolucao', models.TextField(blank=True, help_text='Descrição da resolução do problema', null=True, verbose_name='Resolução')),
                ('atribuicao', models.ForeignKey(help_text='Atribuição de pedido relacionada ao problema', on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='motoristas.atribuicaopedido', verbose_name='Atribuição')),
            ],
            options={
                'verbose_name': 'Problema de Entrega',
                'verbose_name_plural': 'Problemas de Entrega',
                'ordering': ['-criado_em'],
            },
        ),
    ]
