# Generated by Django 5.0.7 on 2025-10-21 19:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_alcool', models.DecimalField(decimal_places=3, default=Decimal('3.499'), help_text='Preço por litro de álcool', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Preço do Álcool (R$/L)')),
                ('preco_gasolina', models.DecimalField(decimal_places=3, default=Decimal('4.449'), help_text='Preço por litro de gasolina', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Preço da Gasolina (R$/L)')),
                ('preco_diesel', models.DecimalField(decimal_places=3, default=Decimal('3.869'), help_text='Preço por litro de diesel', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Preço do Diesel (R$/L)')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Margem de lucro em porcentagem', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Margem de Lucro (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Preço',
                'verbose_name_plural': 'Configurações de Preços',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada geográfica (ex: -23.5505199)', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada geográfica (ex: -46.6333094)', max_digits=10, null=True, verbose_name='Longitude')),
                ('ativa', models.BooleanField(default=True, help_text='Cidade está ativa para operação', verbose_name='Cidade Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['estado', 'nome'],
                'indexes': [models.Index(fields=['estado'], name='rotas_cidad_estado_9a9f87_idx'), models.Index(fields=['ativa'], name='rotas_cidad_ativa_aa811a_idx')],
                'unique_together': {('nome', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.DecimalField(decimal_places=2, help_text='Distância em quilômetros entre as cidades', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Distância (km)')),
                ('tempo_estimado_horas', models.DecimalField(blank=True, decimal_places=2, help_text='Tempo estimado de viagem em horas', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tempo Estimado (horas)')),
                ('pedagio_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total de pedágios na rota', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Pedágio (R$)')),
                ('ativa', models.BooleanField(default=True, help_text='Rota está ativa para operação', verbose_name='Rota Ativa')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre a rota', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_destino', to='rotas.cidade', verbose_name='Cidade de Destino')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_origem', to='rotas.cidade', verbose_name='Cidade de Origem')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['origem__nome', 'destino__nome'],
                'indexes': [models.Index(fields=['origem', 'destino'], name='rotas_rota_origem__93aa69_idx'), models.Index(fields=['ativa'], name='rotas_rota_ativa_a5e8ce_idx')],
                'unique_together': {('origem', 'destino')},
            },
        ),
    ]
