# Generated by Django 5.0.7 on 2025-10-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMudancaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_atual', models.CharField(choices=[('cliente', 'Cliente'), ('motorista', 'Motorista'), ('gerente', 'Gerente'), ('owner', 'Owner')], max_length=20, verbose_name='Perfil Atual')),
                ('perfil_solicitado', models.CharField(choices=[('cliente', 'Cliente'), ('motorista', 'Motorista'), ('gerente', 'Gerente'), ('owner', 'Owner')], max_length=20, verbose_name='Perfil Solicitado')),
                ('justificativa', models.TextField(help_text='Explique o motivo da solicitação de mudança de perfil', verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('observacoes_aprovacao', models.TextField(blank=True, help_text='Observações do gerente/owner sobre a decisão', null=True, verbose_name='Observações da Aprovação')),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_mudanca_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_mudanca_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Solicitação de Mudança de Perfil',
                'verbose_name_plural': 'Solicitações de Mudança de Perfil',
                'ordering': ['-created_at'],
            },
        ),
    ]
