# Generated by Django 5.0.7 on 2025-10-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitacaoMudancaPerfil',
        ),
    ]
