# Generated by Django 5.0.7 on 2025-10-16 19:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacoes_abertas', models.BooleanField(default=True, help_text='Define se o sistema está aceitando novas solicitações de mudança de perfil', verbose_name='Solicitações Abertas')),
                ('mensagem_solicitacoes_fechadas', models.TextField(default='No momento não estamos aceitando novas solicitações. Tente novamente mais tarde.', help_text='Mensagem exibida quando as solicitações estão fechadas', verbose_name='Mensagem quando fechado')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoMudancaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_atual', models.CharField(choices=[('cliente', 'Cliente'), ('motorista', 'Motorista'), ('gerente', 'Gerente'), ('owner', 'Owner')], max_length=20, verbose_name='Role Atual')),
                ('role_solicitada', models.CharField(choices=[('cliente', 'Cliente'), ('motorista', 'Motorista'), ('gerente', 'Gerente'), ('owner', 'Owner')], max_length=20, verbose_name='Role Solicitada')),
                ('justificativa', models.TextField(help_text='Explique por que deseja mudar de perfil', verbose_name='Justificativa')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('tipo_veiculo', models.CharField(blank=True, choices=[('carreta', 'Carreta'), ('van', 'Van'), ('carro', 'Carro'), ('moto', 'Moto')], max_length=20, null=True, verbose_name='Tipo de Veículo')),
                ('modelo_veiculo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Veículo')),
                ('placa_veiculo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo')),
                ('ano_veiculo', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano do Veículo')),
                ('cor_veiculo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor do Veículo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes_admin', models.TextField(blank=True, null=True, verbose_name='Observações do Administrador')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_mudanca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Mudança de Perfil',
                'verbose_name_plural': 'Solicitações de Mudança de Perfil',
                'ordering': ['-created_at'],
            },
        ),
    ]
