# Generated by Django 5.0.7 on 2025-10-30 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomudancaperfil',
            name='cnh_categoria',
            field=models.CharField(blank=True, choices=[('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E')], help_text='Categoria da Carteira Nacional de Habilitação', max_length=1, null=True, verbose_name='Categoria CNH'),
        ),
        migrations.AddField(
            model_name='solicitacaomudancaperfil',
            name='sede_atual',
            field=models.ForeignKey(blank=True, help_text='Cidade onde o motorista estará disponível', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rotas.cidade', verbose_name='Sede Atual'),
        ),
    ]
