# Generated by Django 5.0.7 on 2025-10-16 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carreta', 'Carreta'), ('van', 'Van'), ('carro', 'Carro'), ('moto', 'Moto')], max_length=20, unique=True, verbose_name='Tipo de Veículo')),
                ('combustivel_principal', models.CharField(choices=[('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('alcool', 'Álcool')], max_length=20, verbose_name='Combustível Principal')),
                ('combustivel_alternativo', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('alcool', 'Álcool')], max_length=20, null=True, verbose_name='Combustível Alternativo')),
                ('rendimento_principal', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Rendimento Principal (Km/L)')),
                ('rendimento_alternativo', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Rendimento Alternativo (Km/L)')),
                ('carga_maxima', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Carga Máxima (Kg)')),
                ('velocidade_media', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Velocidade Média (Km/h)')),
                ('reducao_rendimento_principal', models.FloatField(help_text='Redução no rendimento por cada Kg de carga', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Redução de Rendimento por Kg (Principal)')),
                ('reducao_rendimento_alternativo', models.FloatField(blank=True, help_text='Redução no rendimento por cada Kg de carga com combustível alternativo', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Redução de Rendimento por Kg (Alternativo)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Especificação de Veículo',
                'verbose_name_plural': 'Especificações de Veículos',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Ex: Ford, Scania, Honda, etc.', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Ex: Transit, R450, CG 160, etc.', max_length=100, verbose_name='Modelo do Veículo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano de Fabricação')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('ativo', models.BooleanField(default=True, help_text='Veículos inativos não podem ser utilizados em novos pedidos', verbose_name='Veículo Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('especificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='veiculos.especificacaoveiculo', verbose_name='Tipo de Veículo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
