# Generated by Django 5.0.7 on 2025-10-30 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='categoria_minima_cnh',
            field=models.CharField(blank=True, choices=[('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E')], help_text='Categoria mínima de CNH necessária para dirigir este veículo', max_length=1, null=True, verbose_name='Categoria Mínima CNH'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='sede_atual',
            field=models.ForeignKey(blank=True, help_text='Cidade onde o veículo está disponível atualmente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='rotas.cidade', verbose_name='Sede Atual'),
        ),
    ]
