# Generated by Django 5.0.7 on 2025-09-28 20:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_origem', models.CharField(help_text='Cidade de coleta da carga', max_length=255, verbose_name='Cidade de Origem')),
                ('cidade_destino', models.CharField(help_text='Cidade de entrega da carga', max_length=255, verbose_name='Cidade de Destino')),
                ('peso_carga', models.DecimalField(decimal_places=2, help_text='Peso total da carga em quilogramas', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Peso da Carga (kg)')),
                ('prazo_desejado', models.PositiveIntegerField(help_text='Prazo máximo para entrega em dias', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prazo Desejado (dias)')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre a carga (opcional)', null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado'), ('em_transporte', 'Em Transporte'), ('concluido', 'Concluído')], default='pendente', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
