# Generated by Django 5.0.7 on 2025-10-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='opcao',
            field=models.CharField(blank=True, choices=[('economico', 'Mais Econômico'), ('rapido', 'Mais Rápido'), ('custo_beneficio', 'Melhor Custo-Benefício')], help_text='Opção de cotação selecionada pelo cliente', max_length=20, null=True, verbose_name='Opção Escolhida'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='prazo_final',
            field=models.CharField(blank=True, help_text='Prazo calculado pelo gerente', max_length=50, null=True, verbose_name='Prazo Final'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='preco_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço calculado pelo gerente', max_digits=10, null=True, verbose_name='Preço Final'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='veiculo_final',
            field=models.CharField(blank=True, help_text='Veículo definido pelo gerente', max_length=100, null=True, verbose_name='Veículo Final'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('cotacao', 'Cotação Gerada'), ('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado'), ('em_transporte', 'Em Transporte'), ('concluido', 'Concluído')], default='cotacao', max_length=20, verbose_name='Status'),
        ),
    ]
