# Generated by Django 5.0.7 on 2025-10-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_opcao_pedido_prazo_final_pedido_preco_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido_cliente',
            field=models.PositiveIntegerField(default=1, help_text='Número sequencial do pedido por cliente', verbose_name='Número do Pedido (Cliente)'),
        ),
    ]
