# Generated by Django 5.0.7 on 2025-10-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_numero_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cotacao_custo_beneficio_tempo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tempo (h) - Melhor Custo-Benefício'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotacao_custo_beneficio_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor - Melhor Custo-Benefício'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotacao_custo_beneficio_veiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Veículo - Melhor Custo-Benefício'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotacao_economico_tempo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tempo (h) - Mais Econômico'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotacao_economico_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor - Mais Econômico'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotacao_economico_veiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Veículo - Mais Econômico'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotacao_rapido_tempo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tempo (h) - Mais Rápido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotacao_rapido_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor - Mais Rápido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotacao_rapido_veiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Veículo - Mais Rápido'),
        ),
    ]
